version: '3.1'

services:
  db:
    image: mariadb:10.5
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: '${DATABASE_NAME:-database}'
      MYSQL_USER: '${DATABASE_USERNAME:-username}'
      MYSQL_PASSWORD: '${DATABASE_PASSWORD:-password}'
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  db:
